name: CI/CD Docker Build (GHCR)

on:
  push:
    branches:
      - main
      - test-pipeline

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      packages: write      # allow pushing to GHCR
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/asset-management-system-frontend:latest
